name: Publish to npm

on:
  push:
    branches:
      - main # Only run on pushes to main

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "Darsh2126"
          git config --global user.email "darsh2126gajdhar@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}

      - name: Install dependencies
        run: npm ci

      - name: Determine version bump
        id: bump
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Latest commit: $COMMIT_MSG"

          if [[ "$COMMIT_MSG" == *"#major"* ]]; then
            echo "bump=major" >> $GITHUB_ENV
          elif [[ "$COMMIT_MSG" == *"#minor"* ]]; then
            echo "bump=minor" >> $GITHUB_ENV
          else
            echo "bump=patch" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        run: |
          npm version $bump -m "chore(release): %s"
          git push origin HEAD --tags

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}
