name: Publish to npm

on:
  push:
    branches:
      - main   # only run on pushes to main

permissions:
  contents: write   # needed for pushing tags
  packages: write   # needed for npm publish

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure tags are available

      - name: Setup Git identity
        run: |
          git config --global user.name "Darsh2126"
          git config --global user.email "darsh2126gajdhar@gmail.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}

      - name: Install dependencies
        run: npm ci

      # Uncomment if you have tests
      # - name: Run tests
      #   run: npm test

      - name: Build package
        run: npm run build

      - name: Bump version and push tag
        run: |
          npm version patch -m "chore(release): %s"
          git push origin HEAD --tags

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}
