name: Publish to npm

on:
  push:
    branches:
      - main   # runs when you push to main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          always-auth: true

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm run test

      - name: Build package
        run: npm run build

      - name: Bump version and tag
        run: |
          npm version patch -m "chore(release): %s"
          git push origin HEAD --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WORKFLOW }}
